version: '3.3'
services:
    postgres:
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=1
        ports:
            - '5432:5432'
        volumes:
            - '$POSTGRES_HOME/data:/var/lib/postgresql/data'
            - '$POSTGRES_HOME/backup:/backup'
        image: 'ledangtuanbk/postgres:9.6'
